# Spring
spring:
  datasource:
    url: jdbc:h2:file:~/.watchList/WatchList
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true

# RandomOrg
random-org:
  api:
    key: 54d5130b-e8cf-4771-83e5-9ce34e1cf80b

# Shikimori
shikimori:
  api:
    url: https://shikimori.one

# Yandex
yandex:
  api:
    url: https://cloud-api.yandex.net/v1
    disk:
      app-folder: /Приложения/WatchList
