# Spring
spring:
  datasource:
    url: jdbc:h2:file:./.db/WatchList;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        event:
          merge:
            entity_copy_observer: log

# Yandex
yandex:
  api:
    disk:
      app-folder: /Приложения/WatchList/_local

logging:
  level:
    ru:
      demetrious:
        watchlist:
          feign:
            YandexClient: off
          listener:
            MergeEventListener: off
    org:
      hibernate:
        engine:
          internal:
            Cascade: off
        event:
          internal:
            EntityCopyAllowedLoggedObserver: off
        orm:
          jdbc:
            bind: off
